import { describe, expect, it } from '@jest/globals';
import { generateFieldDefsSection, mapDatatype, upsertDatasourceSection } from './fieldDefsGenerator';
import { ExtractedField } from './types';

function field(overrides: Partial<ExtractedField>): ExtractedField {
    return {
        workbook: 'Test.twb',
        datasource: 'Sales DS',
        name: 'Amount',
        ...overrides
    };
}

describe('mapDatatype', () => {
    it('maps Tableau datatypes to declaration types', () => {
        expect(mapDatatype('integer')).toBe('Number');
        expect(mapDatatype('real')).toBe('Number');
        expect(mapDatatype('string')).toBe('String');
        expect(mapDatatype('boolean')).toBe('Boolean');
        expect(mapDatatype('date')).toBe('Date');
        expect(mapDatatype('datetime')).toBe('DateTime');
        expect(mapDatatype('spatial')).toBe('Spatial');
    });

    it('defaults unknown or missing datatypes to String', () => {
        expect(mapDatatype(undefined)).toBe('String');
        expect(mapDatatype('table')).toBe('String');
    });

    it('is case-insensitive', () => {
        expect(mapDatatype('Integer')).toBe('Number');
        expect(mapDatatype('DATETIME')).toBe('DateTime');
    });
});

describe('generateFieldDefsSection', () => {
    it('emits FieldParser-compatible blocks with JSDoc descriptions', () => {
        const section = generateFieldDefsSection(
            [field({ name: 'Amount', datatype: 'real', role: 'measure' })],
            'Sales DS',
            'Test.twb'
        );

        expect(section).toContain('// === Datasource: Sales DS ===');
        expect(section).toContain('[Amount] = Number');
        expect(section).toContain('Amount — measure, real · Sales DS (Test.twb)');
        expect(section).toContain('// === End: Sales DS ===');
    });

    it('prefers caption over internal name', () => {
        const section = generateFieldDefsSection(
            [field({ name: 'amt_1', caption: 'Amount USD', datatype: 'integer' })],
            'DS',
            'Test.twb'
        );
        expect(section).toContain('[Amount USD] = Number');
        expect(section).not.toContain('[amt_1]');
    });

    it('deduplicates by display name, case-insensitively', () => {
        const section = generateFieldDefsSection(
            [
                field({ name: 'Amount', datatype: 'real' }),
                field({ name: 'AMOUNT', datatype: 'string' })
            ],
            'DS',
            'Test.twb'
        );
        expect(section.match(/^\[.*\] = /gm)).toHaveLength(1);
        expect(section).toContain('[Amount] = Number');
    });

    it('skips unnamed fields and names containing ]', () => {
        const section = generateFieldDefsSection(
            [
                field({ name: '', caption: undefined }),
                field({ name: 'Bad ] Name' }),
                field({ name: 'Good' })
            ],
            'DS',
            'Test.twb'
        );
        expect(section.match(/^\[.*\] = /gm)).toHaveLength(1);
        expect(section).toContain('[Good] = String');
    });
});

describe('upsertDatasourceSection', () => {
    const sectionA = generateFieldDefsSection([field({ name: 'A' })], 'DS A', 'Test.twb');
    const sectionB = generateFieldDefsSection([field({ name: 'B' })], 'DS B', 'Test.twb');

    it('creates a new file with a header when content is empty', () => {
        const out = upsertDatasourceSection('', 'DS A', sectionA);
        expect(out).toContain('generated by Tableau Language Support');
        expect(out).toContain('[A] = String');
    });

    it('appends a new datasource section without touching existing ones', () => {
        const first = upsertDatasourceSection('', 'DS A', sectionA);
        const both = upsertDatasourceSection(first, 'DS B', sectionB);
        expect(both).toContain('[A] = String');
        expect(both).toContain('[B] = String');
        expect(both.indexOf('DS A')).toBeLessThan(both.indexOf('DS B'));
    });

    it('replaces an existing section in place', () => {
        const first = upsertDatasourceSection('', 'DS A', sectionA);
        const both = upsertDatasourceSection(first, 'DS B', sectionB);

        const updatedA = generateFieldDefsSection(
            [field({ name: 'A2', datatype: 'boolean' })],
            'DS A',
            'Test.twb'
        );
        const out = upsertDatasourceSection(both, 'DS A', updatedA);

        expect(out).toContain('[A2] = Boolean');
        expect(out).not.toContain('[A] = String');
        expect(out).toContain('[B] = String');
        expect(out.match(/=== Datasource: DS A ===/g)).toHaveLength(1);
    });
});
