/**
 * Field Definitions Generator
 *
 * Turns extracted workbook fields into `fields.d.twbl` declaration blocks that
 * FieldParser can consume (JSDoc description + `[Name] = Type`), giving the
 * LSP hover/completion/lint awareness of the workbook's real fields.
 *
 * The output file is organized into per-datasource sections delimited by
 * marker comments, so regenerating one datasource replaces only its own
 * section and leaves the others untouched.
 */

import { ExtractedField } from './types.js';

/** Tableau datatype -> declaration type used by fields.d.twbl / twbl.d.twbl */
const DATATYPE_MAP: Record<string, string> = {
    integer: 'Number',
    real: 'Number',
    string: 'String',
    boolean: 'Boolean',
    date: 'Date',
    datetime: 'DateTime',
    spatial: 'Spatial'
};

export function mapDatatype(datatype: string | undefined): string {
    return DATATYPE_MAP[(datatype ?? '').toLowerCase()] ?? 'String';
}

function sectionStartMarker(datasource: string): string {
    return `// === Datasource: ${datasource} ===`;
}

function sectionEndMarker(datasource: string): string {
    return `// === End: ${datasource} ===`;
}

/**
 * Generates one datasource's declaration section.
 * Fields are deduplicated by display name (first occurrence wins); fields
 * whose names contain `]` are skipped — they cannot be expressed in the
 * `[Name] = Type` syntax FieldParser reads.
 */
export function generateFieldDefsSection(
    fields: ExtractedField[],
    datasource: string,
    workbook: string
): string {
    const lines: string[] = [sectionStartMarker(datasource)];
    const seen = new Set<string>();

    for (const field of fields) {
        const name = (field.caption ?? field.name ?? '').trim();
        if (!name || name.includes(']')) {
            continue;
        }
        const key = name.toUpperCase();
        if (seen.has(key)) {
            continue;
        }
        seen.add(key);

        const role = field.role ?? 'unknown';
        const datatype = field.datatype ?? 'unknown';
        lines.push('');
        lines.push('/**');
        lines.push(` * ${name} — ${role}, ${datatype} · ${datasource} (${workbook})`);
        lines.push(' */');
        lines.push(`[${name}] = ${mapDatatype(field.datatype)}`);
    }

    lines.push('');
    lines.push(sectionEndMarker(datasource));
    return lines.join('\n');
}

/**
 * Inserts or replaces a datasource's section inside existing file content.
 * Returns the full new file content.
 */
export function upsertDatasourceSection(
    existingContent: string,
    datasource: string,
    section: string
): string {
    const header =
        '/**\n' +
        ' * Workbook field definitions generated by Tableau Language Support.\n' +
        ' * One section per datasource — regenerate a datasource from the\n' +
        ' * Tableau Tools sidebar to refresh its section.\n' +
        ' */\n';

    const start = sectionStartMarker(datasource);
    const end = sectionEndMarker(datasource);

    const content = existingContent.trim();
    if (!content) {
        return `${header}\n${section}\n`;
    }

    const startIdx = content.indexOf(start);
    const endIdx = content.indexOf(end);
    if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
        const before = content.slice(0, startIdx).trimEnd();
        const after = content.slice(endIdx + end.length).trimStart();
        const parts = [before, section, after].filter(p => p !== '');
        return parts.join('\n\n') + '\n';
    }

    return `${content}\n\n${section}\n`;
}
