import { validateWorkbookXml } from '../../parsers/workbookCalculations.js';
import { planWorkbookXmlEdit, workbookRevision } from '../../chat/workbookXmlPlan.js';

const original = '<workbook><datasources/><worksheets><worksheet name="Sales"/></worksheets></workbook>';

describe('strict workbook XML validation', () => {
    it.each([
        ['unescaped ampersand', 'R&D'],
        ['unescaped less-than', 'Revenue < Growth'],
        ['undefined entity', '&unknown;'],
        ['zero character reference', '&#0;'],
        ['surrogate character reference', '&#xD800;'],
        ['out-of-range character reference', '&#x110000;'],
        ['raw control character', '\u0001'],
        ['unpaired high surrogate', '\uD800'],
        ['unpaired low surrogate', '\uDC00'],
    ])('rejects %s before an arbitrary XML edit can be saved', (_description, caption) => {
        expect(() => planWorkbookXmlEdit(original, workbookRevision(original), [
            { oldText: 'name="Sales"', newText: `name="${caption}"` },
        ])).toThrow(/not well formed/i);
    });

    it.each([
        '<workbook><datasources/><caption>R&D</caption></workbook>',
        '<workbook><datasources/><caption>&unknown;</caption></workbook>',
        '<workbook><datasources/><caption>\u0001</caption></workbook>',
        '<workbook><datasources/><caption>text ]]> text</caption></workbook>',
        '<workbook><datasources/><worksheet name="one" name="two"/></workbook>',
    ])('rejects malformed XML text or attributes: %s', xml => {
        expect(() => validateWorkbookXml(xml)).toThrow(/not well formed/i);
    });

    it.each([
        '<!DOCTYPE workbook SYSTEM "https://example.invalid/workbook.dtd">',
        '<!DOCTYPE workbook [<!ENTITY caption "Expanded caption">]>',
        '<!DOCTYPE workbook [<!ENTITY external SYSTEM "file:///unavailable.xml">]>',
    ])('rejects DTD declarations without loading or expanding them: %s', declaration => {
        expect(() => validateWorkbookXml(declaration + original)).toThrow(/DOCTYPE/i);
    });

    it('accepts escaped attributes and supplementary Unicode without rewriting them', () => {
        const caption = 'R&amp;D &lt; Growth &quot;Q1&quot; &apos;2026&apos; &#65; &#x1F4CA; 📊';
        const updated = planWorkbookXmlEdit(original, workbookRevision(original), [
            { oldText: 'name="Sales"', newText: `name="${caption}"` },
        ]);
        expect(updated).toBe(original.replace('name="Sales"', `name="${caption}"`));
    });

    it('accepts Tableau FCP names, namespace attributes, comments and CDATA', () => {
        const xml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Literal data: <!DOCTYPE workbook> &unknown; R&D -->
<?generated by="Tableau"?>
<workbook xmlns:user="http://www.tableausoftware.com/xml/user" user:caption="R&amp;D">
  <datasources><datasource name="orders">
    <_.fcp.ObjectModelEncapsulateLegacy.false...relation name="Data"/>
  </datasource></datasources>
  <caption><![CDATA[R&D < Growth &unknown; <!DOCTYPE workbook>]]></caption>
</workbook>`;
        expect(() => validateWorkbookXml(xml)).not.toThrow();
    });
});
